= Launcher


== Overview
Launcher is an implementation of https://microprofile.io/[MicroProfile].

Launcher 3.0 conforms to MicroProfile 4.1.
Currently supported APIs are as follows:

* Jakarta Contexts and Dependency Injection 2.0
* Jakarta RESTful Web Services 2.1
* Jakarta JSON Binding 1.0
* Jakarta JSON Processing 1.1
* Jakarta Annotations 1.3
* MicroProfile Config 2.0
* MicroProfile Fault Tolerance 3.0
* MicroProfile Health 3.1
* MicroProfile JWT Authentication 1.2
* MicroProfile Metrics 3.0
* MicroProfile OpenAPI 2.0
* MicroProfile OpenTracing 2.0
* MicroProfile Rest Client 2.0

Launcher provides features to run MicroProfile applications and create portable uber (fat) JARs.
For more details, please refer to link:docs/Usage.adoc[].

== Build instructions
----
$ mvn clean install
----

== Usage
Refer to link:docs/Usage.adoc[].

== Downloads
Binary distributions can be obtained from link:https://github.com/fujitsu/launcher/releases[].

== Configuration file example

An example of configuration file which can be used with `--config-file` option is available from link:examples/domain-xml[].
