= Launcher


== Overview
Launcher is an implementation of https://microprofile.io/[MicroProfile].

Launcher 5.0 supports MicroProfile 6.0 and some APIs from Jakarta EE 10.
Currently supported APIs are as follows:

* MicroProfile Config 3.0
* MicroProfile Fault Tolerance 4.0
* MicroProfile Health 4.0
* MicroProfile JWT Authentication 2.1
* MicroProfile Metrics 5.0
* MicroProfile OpenAPI 3.1
* MicroProfile Telemetry 1.0
* MicroProfile Rest Client 3.0
* Jakarta EE 10 Core Profile
* Jakarta Expression Language 5.0
* Jakarta Server Pages 3.1
* Jakarta Servlet 6.0
* Jakarta Standard Tag Library 3.0

Launcher provides features to run MicroProfile applications and create portable uber (fat) JARs.
For more details, please refer to link:docs/Usage.adoc[].

== Build instructions
----
$ mvn clean install
----

== Usage
Refer to link:docs/Usage.adoc[].

== Downloads
Binary distributions can be obtained from link:https://github.com/fujitsu/launcher/releases[].

== Configuration file example

An example of configuration file which can be used with `--config-file` option is available from link:examples/domain-xml[].
